[package]
name = "granita"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A load testing framework for simulating realistic traffic and measuring system performance."
repository = "https://github.com/dilico/granita"

[dependencies]
